# __*Python NumPy Practical*__

## 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [1]:
import numpy as np

# Step 1: Create a 3x3 NumPy array with random integers between 1 and 100
arr = np.random.randint(1, 101, size=(3, 3))

print("Original array:")
print(arr)

# Step 2: Interchange rows and columns (transpose the array)
transposed_arr = arr.T

print("\nTransposed array:")
print(transposed_arr)


Original array:
[[69 12  9]
 [76 19 63]
 [53 95 38]]

Transposed array:
[[69 76 53]
 [12 19 95]
 [ 9 63 38]]


### __Explanation:__
- `np.random.randint(1, 101, size=(3, 3))` : Generates a 3x3 array with random integers between 1 and 100.
- `arr.T` : Transposes the array, interchanging rows and columns.

## 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [1]:
import numpy as np

# Step 1: Generate a 1D NumPy array with 10 elements
arr_1d = np.arange(10)

print("Original 1D array:")
print(arr_1d)

# Step 2: Reshape the 1D array into a 2x5 array
arr_2x5 = arr_1d.reshape(2, 5)

print("\nReshaped into 2x5 array:")
print(arr_2x5)

# Step 3: Reshape the array into a 5x2 array
arr_5x2 = arr_1d.reshape(5, 2)

print("\nReshaped into 5x2 array:")
print(arr_5x2)


Original 1D array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped into 2x5 array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped into 5x2 array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


### __Explanation:__
- `np.arange(10)` : Creates a 1D array with 10 elements ranging from 0 to 9.
- `arr_1d.reshape(2, 5)` : Reshapes the 1D array into a 2x5 array.
- `arr_1d.reshape(5, 2)` : Reshapes the same 1D array into a 5x2 array.

### 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [2]:
# Using np.zeros()

import numpy as np

# Step 1: Create a 4x4 NumPy array with random float values
arr_4x4 = np.random.rand(4, 4)

print("Original 4x4 array:")
print(arr_4x4)

# Step 2: Create a 6x6 array filled with zeros
arr_6x6 = np.zeros((6, 6))

# Step 3: Place the 4x4 array in the center of the 6x6 array
arr_6x6[1:5, 1:5] = arr_4x4

print("\n6x6 array with a border of zeros:")
print(arr_6x6)


Original 4x4 array:
[[0.03569752 0.32639583 0.25546777 0.72655922]
 [0.96200324 0.61665625 0.30419855 0.55371603]
 [0.28305902 0.96317265 0.05642664 0.57500496]
 [0.21664474 0.13666581 0.06470025 0.98553345]]

6x6 array with a border of zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.03569752 0.32639583 0.25546777 0.72655922 0.        ]
 [0.         0.96200324 0.61665625 0.30419855 0.55371603 0.        ]
 [0.         0.28305902 0.96317265 0.05642664 0.57500496 0.        ]
 [0.         0.21664474 0.13666581 0.06470025 0.98553345 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [3]:
# Using np.pad()
# syntax: np.pad(array, pad_width, mode='constant', constant_values=0)

import numpy as np

# Step 1: Create a 4x4 NumPy array with random float values
arr_4x4 = np.random.rand(4, 4)

print("Original 4x4 array:")
print(arr_4x4)

# Step 2: Add a border of zeros around the 4x4 array, resulting in a 6x6 array
arr_6x6 = np.pad(arr_4x4, pad_width=1, mode='constant', constant_values=0)

print("\n6x6 array with a border of zeros:")
print(arr_6x6)


Original 4x4 array:
[[0.51386207 0.74390973 0.16271391 0.92194696]
 [0.8801994  0.30629397 0.70891842 0.11003212]
 [0.99967227 0.59877709 0.21145699 0.36202481]
 [0.84726408 0.47704786 0.1014806  0.7550267 ]]

6x6 array with a border of zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.51386207 0.74390973 0.16271391 0.92194696 0.        ]
 [0.         0.8801994  0.30629397 0.70891842 0.11003212 0.        ]
 [0.         0.99967227 0.59877709 0.21145699 0.36202481 0.        ]
 [0.         0.84726408 0.47704786 0.1014806  0.7550267  0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


### __Explanation__
- `np.random.rand(4, 4)` : Creates a 4x4 array with random float values between 0 and 1.
- `np.pad()` : Adds padding around the array.
- `pad_width=1` : Adds a border of width 1.
    - mode='constant', constant_values=0: Fills the border with zeros.

### __Padding Parameters:__
- array: The input array to be padded.
- pad_width: The number of values padded to the edges of each axis. It can be:
    - A single integer: Pads the same width on every axis.
    - A tuple of two integers: Specifies different padding for before and after each axis.
    - A tuple of tuples: Specifies padding for each axis separately.
- mode: The method to use for padding. Some common options:
    - 'constant': Pads with a constant value (default value is 0).
    - 'edge': Pads using the edge values of the array.
    - 'linear_ramp': Pads with a linear ramp of values.
    - 'symmetric': Pads with values symmetrically from the edge.
- constant_values: When using 'constant' mode, this specifies the value(s) to use for padding. Default is 0.    

## 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [6]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
arr = np.arange(10, 65, 5)

print(arr)

# np.arange(10, 65, 5): Generates an array starting at 10, up to (but not including) 65, with a step of 5.

[10 15 20 25 30 35 40 45 50 55 60]


In [7]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5 using linspace
arr = np.linspace(10, 60, num=11, dtype=int)

print(arr)

# np.linspace(10, 60, num=11, dtype=int): Generates 11 evenly spaced values from 10 to 60, inclusive, and converts them to integers.

[10 15 20 25 30 35 40 45 50 55 60]


## 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

In [10]:
import numpy as np

# Create a NumPy array of strings
arr = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations using np.char
upper_case = np.char.upper(arr)         # Uppercase
lower_case = np.char.lower(arr)         # Lowercase
title_case = np.char.title(arr)         # Title case
capitalize_case = np.char.capitalize(arr)  # Capitalize the first letter

# Print the results
print("Original array:")
print(arr)
print("\nUppercase:")
print(upper_case)
print("\nLowercase:")
print(lower_case)
print("\nTitle case:")
print(title_case)
print("\nCapitalized:")
print(capitalize_case)


Original array:
['python' 'numpy' 'pandas']

Uppercase:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase:
['python' 'numpy' 'pandas']

Title case:
['Python' 'Numpy' 'Pandas']

Capitalized:
['Python' 'Numpy' 'Pandas']


## 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [11]:
import numpy as np

# Create a NumPy array of strings
words = np.array(['python', 'numpy', 'pandas'])

# Join characters of each string in the array with a space
joined = np.char.join(' ', words)

print(joined)


['p y t h o n' 'n u m p y' 'p a n d a s']


__Syntax:__  `np.char.join(sep, arr)`

- sep: A string that separates the elements. This string will be inserted between the characters or strings being joined.
- arr: The input array of strings or characters.


## 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [12]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Element-wise addition
addition = array1 + array2

# Element-wise subtraction
subtraction = array1 - array2

# Element-wise multiplication
multiplication = array1 * array2

# Element-wise division
division = array1 / array2

# Print the results
print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\nElement-wise Addition:")
print(addition)
print("\nElement-wise Subtraction:")
print(subtraction)
print("\nElement-wise Multiplication:")
print(multiplication)
print("\nElement-wise Division:")
print(division)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Element-wise Addition:
[[ 8 10 12]
 [14 16 18]]

Element-wise Subtraction:
[[-6 -6 -6]
 [-6 -6 -6]]

Element-wise Multiplication:
[[ 7 16 27]
 [40 55 72]]

Element-wise Division:
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


## 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [13]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diagonal(identity_matrix)

# Print the results
print("5x5 Identity Matrix:")
print(identity_matrix)
print("\nDiagonal Elements:")
print(diagonal_elements)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


## 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

In [16]:
import numpy as np

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1000, size=100)

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Find all prime numbers in the array
prime_numbers = np.array([num for num in random_integers if is_prime(num)])

# Print the results
print("Random Integers:")
print(random_integers)
print("\nPrime Numbers:")
print(prime_numbers)


Random Integers:
[ 34 148 241 972 570 270 203 998 902 640 150 503 693 772 357 285 688 503
 220 749  88 213 896 208 278 155 702 743 207 436 952  20 709 329 605 219
 831 426 237 504 104 306  88 555 508 894 803 434 266 720 291 614 962 919
 218 466 816 953 714  58 345 780 386 107 965 469 849 656 515 828 724 923
 387 726  29 732  27 157 847 700 292 108 290 545 858 440 442 149 661 734
 967 280 577 317 639  79 819 959 954 373]

Prime Numbers:
[241 503 503 743 709 919 953 107  29 157 149 661 967 577 317  79 373]


## 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [22]:
import numpy as np

# Create a NumPy array with 30 random daily temperatures (e.g., between 15°C and 35°C)
daily_temperatures = np.random.randint(15, 36, size=30)

# Use the first 28 days for 4 full weeks
weeks = daily_temperatures[:28].reshape(4, 7)

# Calculate weekly averages for the first 4 full weeks
weekly_averages = weeks.mean(axis=1)

# Calculate the average for the remaining 2 days
last_2_days_avg = daily_temperatures[28:].mean()

# Print daily temperatures, weekly averages, and the average for the last 2 days
print("Daily Temperatures for the Month:")
print(daily_temperatures)

print("\nWeekly Averages (first 4 weeks):")
print(weekly_averages)

print(f"\nAverage for the last 2 days: {last_2_days_avg}")


Daily Temperatures for the Month:
[32 35 19 20 34 21 17 34 35 34 30 21 15 16 27 28 26 28 33 15 30 15 21 25
 25 21 29 17 26 32]

Weekly Averages (first 4 weeks):
[25.42857143 26.42857143 26.71428571 21.85714286]

Average for the last 2 days: 29.0
